### PR TITLE
Pull request for tedla001

### PR DESCRIPTION
**Pull request by Triveniedla**

### CODE REVIEW

**Comment by fanchyna** [comment]
Please use a name different from mine. See the requirement in my assignment.

**Comment by Triveniedla** [comment]
I have followed your instructions in section 2.2 and section 2.3. 

I have also renamed tedla001.md to tedla001.txt.

**Comment by fanchyna** [comment]
Please only keep the github link and remove "**Github link:**" and "**name**" from your file.

**Comment by Triveniedla** [comment]
Professor,

I have removed "Github link:" and "name" from my file.

**Review by fanchyna — APPROVED** [review]

**Pull request merged**
